In [6]:
import numpy as np

In [2]:
qtde = [2, 5, 10, 20, 35]
custo = [100, 150, 450, 320, 195]

In [8]:
arr1 = np.array(qtde)

In [7]:
arr2 = np.array(custo)

In [9]:
estoque = arr1*arr2

In [10]:
estoque

array([ 200,  750, 4500, 6400, 6825])

In [11]:
custo = [100,200,300,400]
venda = [125,235,355,490]

In [12]:
arr3 = np.array(custo)

In [13]:
arr4 = np.array(venda)

In [14]:
lucro = arr4 - arr3

In [15]:
lucro

array([25, 35, 55, 90])

In [17]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [19]:
np.arange(10, 101,2, dtype=float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

In [20]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.random.rand(10)

array([0.25102709, 0.43838554, 0.71755296, 0.3363647 , 0.44323161,
       0.36377465, 0.41789826, 0.17163202, 0.34691806, 0.48646997])

In [23]:
np.random.randn(10)

array([-1.09745828,  1.40962724, -1.27986911, -2.93713426, -0.91393788,
        1.03821736,  0.34995524, -1.50133617,  0.24152796,  1.17355955])

In [24]:
np.random.randint(10,100,30)

array([46, 20, 17, 60, 21, 83, 98, 71, 72, 22, 39, 16, 84, 43, 69, 12, 80,
       47, 65, 84, 71, 46, 31, 83, 34, 19, 15, 13, 75, 32])

In [25]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr = np.arange(1, 11,dtype=int)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#5

In [31]:
arr[4]

5

In [32]:
#3 to 5

In [33]:
arr[2:5]

array([3, 4, 5])