In [6]:
import numpy as np

In [2]:
qtde = [2, 5, 10, 20, 35]
custo = [100, 150, 450, 320, 195]

In [8]:
arr1 = np.array(qtde)

In [7]:
arr2 = np.array(custo)

In [9]:
estoque = arr1*arr2

In [10]:
estoque

array([ 200,  750, 4500, 6400, 6825])

In [11]:
custo = [100,200,300,400]
venda = [125,235,355,490]

In [12]:
arr3 = np.array(custo)

In [13]:
arr4 = np.array(venda)

In [14]:
lucro = arr4 - arr3

In [15]:
lucro

array([25, 35, 55, 90])

In [17]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [19]:
np.arange(10, 101,2, dtype=float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

In [20]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.random.rand(10)

array([0.25102709, 0.43838554, 0.71755296, 0.3363647 , 0.44323161,
       0.36377465, 0.41789826, 0.17163202, 0.34691806, 0.48646997])

In [23]:
np.random.randn(10)

array([-1.09745828,  1.40962724, -1.27986911, -2.93713426, -0.91393788,
        1.03821736,  0.34995524, -1.50133617,  0.24152796,  1.17355955])

In [24]:
np.random.randint(10,100,30)

array([46, 20, 17, 60, 21, 83, 98, 71, 72, 22, 39, 16, 84, 43, 69, 12, 80,
       47, 65, 84, 71, 46, 31, 83, 34, 19, 15, 13, 75, 32])

In [25]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr = np.arange(1, 11,dtype=int)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#5

In [31]:
arr[4]

5

In [32]:
#3 to 5

In [33]:
arr[2:5]

array([3, 4, 5])

In [34]:
arr[:5]

array([1, 2, 3, 4, 5])

In [36]:
arr5 = np.random.randint(10,50, size=(3,3))

In [37]:
arr5

array([[19, 14, 30],
       [27, 42, 19],
       [33, 40, 11]])

In [38]:
#42

In [39]:
arr5[1][1]

42

In [40]:
#33 and 40

In [41]:
arr5[2][0:2]

array([33, 40])

In [42]:
arr6 = np.random.randint(1, 101, size=(10,10))

In [43]:
arr6

array([[ 52,  54,  67,  37,  65,  53,  84,  93,   8,   8],
       [ 29,  24,  89,  68,  28,   6,  91,   8,  81,  12],
       [  5,  52,  56,  93,  91,  96,   7,  53,  46, 100],
       [ 16,   1,  27,  60,   2,  46,  86,  74,  38,  75],
       [ 20,  14,  78,  99,  86,  57,  51,  19,  87,  54],
       [ 82,  39,  56,  55,  61,  83,  71,  97,  45,  96],
       [ 70,  96,  79,  20,  26,  39,  73,  26,  77,  52],
       [ 76,  76,  61,  19,  41,  64,  87,  51,  16,  55],
       [ 68,  78,  94,  27,  64,  35,  73, 100,  34,  14],
       [ 26,   3,  88,  50,  55,  74,  88,  86,  89,  44]])

In [44]:
#99

In [47]:
arr6[4,3]

99

In [48]:
#93,   8,   8
#8,  81,  12
#53,  46, 100

In [49]:
arr6[0:3,7:]

array([[ 93,   8,   8],
       [  8,  81,  12],
       [ 53,  46, 100]])

In [50]:
#7,  53,  46
#86,  74,  38

In [56]:
arr6[2:4, 6:9]

array([[ 7, 53, 46],
       [86, 74, 38]])

In [57]:
#all numbers in lines 2, 4 and 5

In [59]:
arr6[[1,3,4]]

array([[29, 24, 89, 68, 28,  6, 91,  8, 81, 12],
       [16,  1, 27, 60,  2, 46, 86, 74, 38, 75],
       [20, 14, 78, 99, 86, 57, 51, 19, 87, 54]])

In [60]:
cadastro = np.random.randint(15, 51, size=(50,10))

In [61]:
cadastro

array([[32, 43, 34, 39, 26, 40, 34, 32, 15, 47],
       [31, 42, 32, 41, 25, 26, 40, 48, 31, 21],
       [46, 27, 41, 23, 45, 50, 35, 50, 45, 44],
       [24, 27, 47, 17, 22, 39, 20, 40, 29, 28],
       [45, 16, 43, 32, 27, 21, 24, 43, 17, 40],
       [15, 50, 42, 17, 21, 46, 33, 21, 35, 46],
       [32, 17, 49, 15, 27, 39, 15, 36, 41, 38],
       [15, 29, 32, 25, 38, 30, 35, 50, 32, 34],
       [44, 24, 40, 36, 30, 23, 19, 21, 31, 36],
       [26, 39, 40, 21, 27, 41, 21, 20, 27, 29],
       [47, 43, 20, 44, 43, 50, 16, 39, 37, 15],
       [38, 37, 34, 40, 17, 46, 48, 17, 36, 32],
       [39, 44, 22, 22, 49, 21, 36, 28, 36, 42],
       [45, 32, 40, 42, 36, 35, 19, 15, 38, 27],
       [47, 22, 23, 48, 20, 44, 39, 31, 38, 48],
       [24, 25, 22, 39, 48, 30, 50, 34, 29, 38],
       [33, 15, 44, 23, 43, 30, 23, 15, 29, 45],
       [22, 35, 41, 33, 30, 18, 49, 30, 25, 15],
       [44, 39, 20, 39, 39, 17, 39, 32, 17, 15],
       [17, 46, 34, 37, 30, 33, 46, 15, 35, 49],
       [41, 18, 17, 

In [70]:
cadastro_maior_idade = cadastro >= 18

In [67]:
cadastro[cadastro_maior_idade]

array([32, 43, 34, 39, 26, 40, 34, 32, 47, 31, 42, 32, 41, 25, 26, 40, 48,
       31, 21, 46, 27, 41, 23, 45, 50, 35, 50, 45, 44, 24, 27, 47, 22, 39,
       20, 40, 29, 28, 45, 43, 32, 27, 21, 24, 43, 40, 50, 42, 21, 46, 33,
       21, 35, 46, 32, 49, 27, 39, 36, 41, 38, 29, 32, 25, 38, 30, 35, 50,
       32, 34, 44, 24, 40, 36, 30, 23, 19, 21, 31, 36, 26, 39, 40, 21, 27,
       41, 21, 20, 27, 29, 47, 43, 20, 44, 43, 50, 39, 37, 38, 37, 34, 40,
       46, 48, 36, 32, 39, 44, 22, 22, 49, 21, 36, 28, 36, 42, 45, 32, 40,
       42, 36, 35, 19, 38, 27, 47, 22, 23, 48, 20, 44, 39, 31, 38, 48, 24,
       25, 22, 39, 48, 30, 50, 34, 29, 38, 33, 44, 23, 43, 30, 23, 29, 45,
       22, 35, 41, 33, 30, 18, 49, 30, 25, 44, 39, 20, 39, 39, 39, 32, 46,
       34, 37, 30, 33, 46, 35, 49, 41, 18, 48, 49, 42, 35, 49, 24, 27, 24,
       39, 31, 45, 44, 40, 25, 24, 19, 27, 30, 36, 32, 43, 18, 45, 40, 29,
       40, 26, 24, 26, 46, 33, 31, 20, 34, 32, 20, 45, 45, 42, 32, 40, 41,
       38, 24, 40, 38, 30

In [65]:
cadastro[cadastro>=18]

array([32, 43, 34, 39, 26, 40, 34, 32, 47, 31, 42, 32, 41, 25, 26, 40, 48,
       31, 21, 46, 27, 41, 23, 45, 50, 35, 50, 45, 44, 24, 27, 47, 22, 39,
       20, 40, 29, 28, 45, 43, 32, 27, 21, 24, 43, 40, 50, 42, 21, 46, 33,
       21, 35, 46, 32, 49, 27, 39, 36, 41, 38, 29, 32, 25, 38, 30, 35, 50,
       32, 34, 44, 24, 40, 36, 30, 23, 19, 21, 31, 36, 26, 39, 40, 21, 27,
       41, 21, 20, 27, 29, 47, 43, 20, 44, 43, 50, 39, 37, 38, 37, 34, 40,
       46, 48, 36, 32, 39, 44, 22, 22, 49, 21, 36, 28, 36, 42, 45, 32, 40,
       42, 36, 35, 19, 38, 27, 47, 22, 23, 48, 20, 44, 39, 31, 38, 48, 24,
       25, 22, 39, 48, 30, 50, 34, 29, 38, 33, 44, 23, 43, 30, 23, 29, 45,
       22, 35, 41, 33, 30, 18, 49, 30, 25, 44, 39, 20, 39, 39, 39, 32, 46,
       34, 37, 30, 33, 46, 35, 49, 41, 18, 48, 49, 42, 35, 49, 24, 27, 24,
       39, 31, 45, 44, 40, 25, 24, 19, 27, 30, 36, 32, 43, 18, 45, 40, 29,
       40, 26, 24, 26, 46, 33, 31, 20, 34, 32, 20, 45, 45, 42, 32, 40, 41,
       38, 24, 40, 38, 30

In [68]:
len(cadastro[cadastro>=18])

449

In [71]:
condicao = (cadastro>=20)

In [72]:
extraido = np.extract(condicao, cadastro)

In [73]:
extraido

array([32, 43, 34, 39, 26, 40, 34, 32, 47, 31, 42, 32, 41, 25, 26, 40, 48,
       31, 21, 46, 27, 41, 23, 45, 50, 35, 50, 45, 44, 24, 27, 47, 22, 39,
       20, 40, 29, 28, 45, 43, 32, 27, 21, 24, 43, 40, 50, 42, 21, 46, 33,
       21, 35, 46, 32, 49, 27, 39, 36, 41, 38, 29, 32, 25, 38, 30, 35, 50,
       32, 34, 44, 24, 40, 36, 30, 23, 21, 31, 36, 26, 39, 40, 21, 27, 41,
       21, 20, 27, 29, 47, 43, 20, 44, 43, 50, 39, 37, 38, 37, 34, 40, 46,
       48, 36, 32, 39, 44, 22, 22, 49, 21, 36, 28, 36, 42, 45, 32, 40, 42,
       36, 35, 38, 27, 47, 22, 23, 48, 20, 44, 39, 31, 38, 48, 24, 25, 22,
       39, 48, 30, 50, 34, 29, 38, 33, 44, 23, 43, 30, 23, 29, 45, 22, 35,
       41, 33, 30, 49, 30, 25, 44, 39, 20, 39, 39, 39, 32, 46, 34, 37, 30,
       33, 46, 35, 49, 41, 48, 49, 42, 35, 49, 24, 27, 24, 39, 31, 45, 44,
       40, 25, 24, 27, 30, 36, 32, 43, 45, 40, 29, 40, 26, 24, 26, 46, 33,
       31, 20, 34, 32, 20, 45, 45, 42, 32, 40, 41, 38, 24, 40, 38, 30, 48,
       46, 21, 20, 36, 21